/**
 * Install the committed hooks into this clone's `.git/hooks/`.
 *
 * Two ways exist to make a committed hook run, and this takes the third:
 *
 *   - copy the script into `.git/hooks/` — then the copy drifts from the source
 *     the first time the source changes, silently;
 *   - set `core.hooksPath` — a git *config* change, which this project does not
 *     make on someone's machine as a side effect of a helper script;
 *   - install a three-line **shim** that execs the committed script. No drift, no
 *     config change, and `.git/hooks/pre-push` is readable enough to audit at a
 *     glance. That is what this does.
 *
 * Refuses to overwrite a hook it did not write, unless `--force`. Someone else's
 * pre-push hook is their work, and clobbering it to install a visibility check
 * would be a poor trade.
 *
 * Usage:
 *   node scripts/install-hooks.mjs
 *   node scripts/install-hooks.mjs --force
 *   node scripts/install-hooks.mjs --uninstall
 */
import { execFileSync } from 'node:child_process';
import { chmodSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';

const argv = process.argv.slice(2);
const force = argv.includes('--force');
const uninstall = argv.includes('--uninstall');

const HOOKS = ['pre-push'];
const MARKER = 'webmcp-gauge:scripts/hooks';

const gitDir = (() => {
  try {
    return resolve(execFileSync('git', ['rev-parse', '--absolute-git-dir'], { encoding: 'utf8' }).trim());
  } catch (error) {
    console.error(`not a git repository, or git is unavailable: ${error.message}`);
    process.exit(2);
  }
})();

const hooksDir = join(gitDir, 'hooks');
const sourceDir = resolve('scripts/hooks');

// Relative to the worktree root, which is where git runs a hook from, so the shim
// works for a worktree in any directory and for a linked worktree too.
const shimFor = (name) => `#!/bin/sh
# ${MARKER} — generated by scripts/install-hooks.mjs. Edit the source, not this file.
exec "$(git rev-parse --show-toplevel)/scripts/hooks/${name}" "$@"
`;

mkdirSync(hooksDir, { recursive: true });

let changed = 0;
for (const name of HOOKS) {
  const target = join(hooksDir, name);
  const source = join(sourceDir, name);

  if (uninstall) {
    if (!existsSync(target)) {
      console.log(`${name}: not installed`);
      continue;
    }
    if (!readFileSync(target, 'utf8').includes(MARKER) && !force) {
      console.log(`${name}: left alone — .git/hooks/${name} is not ours (use --force to remove it anyway)`);
      continue;
    }
    rmSync(target);
    console.log(`${name}: removed`);
    changed += 1;
    continue;
  }

  if (!existsSync(source)) {
    console.error(`${name}: no source at scripts/hooks/${name}`);
    process.exit(2);
  }

  if (existsSync(target)) {
    const current = readFileSync(target, 'utf8');
    if (current.includes(MARKER)) {
      writeFileSync(target, shimFor(name), 'utf8');
      chmodSync(target, 0o755);
      console.log(`${name}: shim refreshed`);
      changed += 1;
      continue;
    }
    if (!force) {
      console.log(`${name}: SKIPPED — .git/hooks/${name} already exists and is not ours. Inspect it, then re-run with --force.`);
      continue;
    }
  }

  writeFileSync(target, shimFor(name), 'utf8');
  // Harmless on Windows, required everywhere else.
  chmodSync(target, 0o755);
  // The source has to be executable too, since the shim execs it directly.
  chmodSync(source, 0o755);
  console.log(`${name}: installed → ${target}`);
  changed += 1;
}

console.log(
  changed === 0
    ? '\nnothing changed.'
    : uninstall
      ? '\nhooks removed. Nothing gates a push now.'
      : '\nInstalled. A push now runs the visibility gate first; see scripts/hooks/pre-push for what it refuses and why.'
);
